version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: monkeydluffy
      POSTGRES_PASSWORD: OnePiece123.
      POSTGRES_DB: onepiece_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monkeydluffy -d onepiece_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8502:8502"
    environment:
      DATABASE_URL: postgresql://monkeydluffy:OnePiece123.@db:5432/onepiece_db
    volumes:
      - ./backend/app:/app/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: http://backend:8502
    volumes:
      - ./frontend/src:/app
    depends_on:
      - backend

volumes:
  postgres_data: